version: 0.2
env:
  parameter-store:
    TOKEN: /github/token
phases:
  build:
    commands:
      - echo $TOKEN
      - ls
      - pwd
      - which bash
      - chmod 777 git_changes.sh
      - ls -ltr git_changes.sh
      #- bash git_changes.sh
      - git diff --name-only HEAD HEAD~1