version: 0.2
env:
  parameter-store:
    TOKEN: /github/token
phases:
  build:
    commands:
      - chmod 777 git_changes.sh
      - which bash
      - bash git_changes.sh
      - ls
      - cat test.txt
      #- git diff --name-only HEAD HEAD\~1