version: 0.2
env:
  parameter-store:
    TOKEN: /github/token
phases:
  build:
    commands:
      - chmod 777 git_changes.sh
      - git@github.com:ervaneet82/terraform.git
      - cd terraform
      - git fetch --all
      - git pull --all
      - git log
     # - /usr/bin/cat git_changes.sh
     # - /usr/bin/bash -x git_changes.sh
     # - /usr/bin/cat test.txt
      #- git diff --name-only HEAD HEAD\~1