version: 0.2
env:
  env:
    parameter-store:
      TOKEN: /github/token
phases:
  build:
    commands:
      - echo $TOKEN
      - /usr/bin/curl -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/ervaneet82/terraform/commits