pipeline {
  agent any
  environment {
    SVC_ACCOUNT_KEY = credentials('google-terraform')
  }
  stages {
    stage('Checkout') {
      steps {
        withCredentials([file(credentialsId: 'google-terraform', variable: 'mySecretFile')]) {
        // some block can be a groovy block as well and the variable will be available to the groovy script
        sh '''
            echo "This is the directory of the secret file $mySecretFile"
            echo "This is the content of the file `cat $mySecretFile`"
         '''
       }
     }
    }
    stage('TF Plan') {
      steps {
          sh '''
            cd my_google_terraform
            terraform init
            terraform plan -out myplan
          '''
      }
    }
  }
}
