pipeline {
  agent any
  environment {
    SVC_ACCOUNT_KEY = credentials('google-terraform')
  }
  stages {
    stage('Checkout') {
      steps {
        withCredentials([file(credentialsId: 'google-terraform', variable: 'mySecretFile')]) {
        // some block can be a groovy block as well and the variable will be available to the groovy script
        sh '''
          pwd
          echo "This is the content of the file `cat $mySecretFile`"
          cd my_google_terraform
          cat $mySecretFile > google.json
         '''
       }
     }
    }
    stage('google-ssh-key') {
      steps {
        withCredentials([file(credentialsId: 'google-ssh-pub-key', variable: 'mykey')]) {
        // some block can be a groovy block as well and the variable will be available to the groovy script
        sh '''
          cd my_google_terraform
          cat $mykey > mykey.pub
         '''
       }
     }
    }
    stage('TF Plan') {
      steps {
        sh '''
          cd my_google_terraform
          terraform init
          terraform plan -out myplan
          '''
      }
    }
    stage('Approval') {
      steps {
        script {
          def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
        }
      }
    }
    stage('TF Apply') {
      steps {
          sh '''
          cd my_google_terraform
          terraform apply -input=false myplan
          '''
        }
    }
  }
}
